apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.postgres_cast.name }} #postgres-cast-configmap
  labels:
    app: {{ .Values.Deployment.cast_db.name }} #postgres-cast-db
  namespace: {{ .Values.namespace }} #dev
data:
  POSTGRES_USER: {{ .Values.configmap.postgres_cast.POSTGRES_PASSWORD}} #"cast"
  POSTGRES_PASSWORD: {{ .Values.configmap.postgres_cast.POSTGRES_PASSWORD }} #"password"
  POSTGRES_DB: {{ .Values.configmap.postgres_cast.POSTGRES_DB }} #"cast_db"

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.cast_service.name }}  #cast-service-config
  namespace: {{ .Values.namespace }} #dev
  labels:
    app: {{ .Values.Deployment.cast_service.name }} #cast-svc-deploy
data:
  DATABASE_URI: {{ .Values.configmap.cast_service.uri }} #"postgresql://cast:password@pg-cast-service/cast_db"

